### PR TITLE
 Merge datePicker, CSS textEditor changes, changes to Lesson Editor, and Lesson Creator

### PR DESCRIPTION
**Pull request by raidenwilliams**

### CODE REVIEW

**Comment by patwu22** [comment]
client/yarn.lock still says merge conflict. Also, there are two yarn.lock in the pr. Try add **yarn.lock** to both .gitignore under the top folder and the client folder.

Besides, I saw **description, releaseDate, closeDate** entry field were added to the database. Since we are kinda not supposed to change the current table and the **expectations** should actually be the **description** as per what the prof said in our last demo, I think you probably should delete the description field and clean up everything about **description** in client/src/Utils/requests.js so that the documents in /server do not conflict.

**Comment by patwu22** [comment]
There is an easier way to do this tho. Do a pr from main branch to your branch. Solve the conflicts locally. And then do this pr to main branch again.

**Comment by raidenwilliams** [comment]
Please review, should be able to automatically merge after review.

**Review by patwu22 — APPROVED** [review]
LGTM

**Pull request merged**
